In [1]:
import numpy as np

***Python Lists***

In [2]:
# here are 2 lists

first_List  = [22.5, 55.3, 15.3, 64.3]
second_List = [5.2, 22.2, 78.9, 47.1]


# print the calculation of 22.5 * 5.2 but you have to do each
# element individually which becomes a lengthy process
# this is where NumPy is better to do calculations
# over the entire array

print(first_List[0]* second_List[0])
print(first_List[1]* second_List[1])
# remember that python is zero indexed 

117.0
1227.6599999999999


***Lists V NP Arrays***

In [3]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# standard python list above

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#np array

print(my_list)
print(array)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
my_list = [1, 2, 3]

print(my_list + my_list)  
# lists the elements to the end of the list instead of adding them like arrays

[1, 2, 3, 1, 2, 3]


In [5]:
my_list2 = np.array([1,2,3])
#Set up as NP array

print(my_list2 + my_list2)

[2 4 6]


In [7]:
array = np.array([1, 2, 3, 4]) 
# array is made up of numbers

print(array) # prints all the data
print(array * 2) # prints each entity in the array * 2
print(array * array) 
# prints each entity in the array by itself

# really useful when dealing with large data sets to run calculations on arrays faster and less memory than a SpreadSheet
# faster than humans = AI

[1 2 3 4]
[2 4 6 8]
[ 1  4  9 16]


***One-Dimensional and Two-Dimensional Arrays***

In [8]:
# 1 dimensional array
array1 = np.array([1, 2, 3, 4, 5])

print(array1)

[1 2 3 4 5]


In [9]:
# 2 dimensional array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array2)

# look at how it prints a 2d array [[]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***Slicing***

In [11]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[1:5]) 
# slices data from index 1 to 4  - 0 indexed and discounts final number

[2 3 4 5]


In [10]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array1[4:]) 
# slices data from position 4 onwards

[5 6 7 8 9]


In [12]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7])

print(array2[:4])  
# slices unitl index/position 4

[1 2 3 4]


In [13]:
slice = np.array([1,2,3,4,5,6,7,8]) 
# slices from 1 to 8 in increments of 2
print(slice[1:8:2])

[2 4 6 8]


***NP Zeros***

In [14]:
zeros = np.zeros(10)  # single list/vector

print (zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
zeros1 = np.zeros((4, 4)) # 4 by 4 matrix 

print(zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


***NP Ones***

In [16]:
ones = np.ones(8)  # single list/vector

print (ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
matrix = np.ones((3, 3)) # 3 by 3 matrix 

print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


***NP Random Array***

In [18]:
random = np.random.rand(3,4) #3 rows, 4 columns

print (random)

[[0.0938706  0.06635312 0.34401923 0.19629109]
 [0.3589829  0.19703058 0.92769055 0.90482812]
 [0.86254669 0.12480651 0.36460697 0.25089658]]


***NP Eye***

In [19]:
eye = np.eye (6)

print (eye)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


***NP Arange***

In [20]:
x = np.arange(10)

print(x) # evenly spaced array 

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# add a 2nd argument start = 5, stop = 15, again no step added
array1 = np.arange(5, 16)

print(array1) # still  has step size of 1

[ 5  6  7  8  9 10 11 12 13 14 15]


In [22]:
# 3rd argument to add step
array2 = np.arange(0, 15, 2)

print(array2)

[ 0  2  4  6  8 10 12 14]


In [23]:
# can pass decimals as increments - use nplinspace for decimal arrays though
array3 = np.arange(0, 15, 0.5)

print(array3)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5]


***Reshaping***

In [24]:
# 1D to 2D
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newArray = array.reshape(4, 3) 
# rows then columns when creating the matrix

print(newArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
# 1D array to 3D array
array1 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

newArray1 = array1.reshape(2, 3, 2) 
# 2 matrices, 3 rows and 2 columns. 
#Must use this order

print(newArray1)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [26]:
reshape = np.arange(1, 26).reshape(5,5)

print(reshape)

# has to have value the same length as the matrix
# e.g. 1-26 would print 25 entities and the matrix would by 5 by 5 - 5*5 = 25!
# remember it does not count the stop 26!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
array = np.arange(0,5)

print(array)

print(array - 10)
print("Multiply :", array * 10)
print("Divide :", array / 10)
print("Power :", array ** 2)

[0 1 2 3 4]
[-10  -9  -8  -7  -6]
Multiply : [ 0 10 20 30 40]
Divide : [0.  0.1 0.2 0.3 0.4]
Power : [ 0  1  4  9 16]


In [28]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


***NP Dot***

In [29]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


***NP Sum***

In [30]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)
print(c)

total_sum = np.sum(c)
print(total_sum)


[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [ ]:
# you can use np.sum on any matrix.
print(a)
sum1 = np.sum(a)
print(sum1)

***Sum by Row/Column***

In [31]:
#by column
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c, axis = 0)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[603 648 693]


In [32]:
#by row
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a, b)

print(c)

e = np.sum(c,axis = 1)

print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]
